# Introduction to Python - NumPy

In [1]:
# Author: Matthias Huber (huber@ifo.de), Alex Schmitt (schmitt@ifo.de)

import datetime
print('Last update: ' + str(datetime.datetime.today()))

Last update: 2017-05-11 12:17:37.392842


## NumPy

NumPy is probably the most widely used library for numerical programming and scientific computing in Python. Its documentation can be found here:

In [2]:
# import webbrowser
# url = 'http://docs.scipy.org/doc/numpy/reference/'
# webbrowser.open(url)

Many people in the community will usually import it with an abbreviated name, using **import** with the **as** keyword. 

In [3]:
import numpy as np

## Motivation

Suppose we would like to implement the popular Cobb-Douglas production function $y = f(E, L) = E^\alpha L^{1 - \alpha}$ as a Python function. Based on what we have learnt so far, this is straight forward:

In [4]:
def cobb_douglas(E, L, alpha = 0.5):
    """
    Implements the Cobb-Douglas production function: y = E**alpha * L**alpha
    """
    y = E**alpha * L**(1 - alpha)
    return y

print(cobb_douglas(10, 1))

3.1622776601683795


Note that the function allows $E$ and $L$ to be scalar numbers. It would be nice to also be able to use the function on *arrays* (or *vectors*). For example, we may be interested in evaluating different combinations of $E$ and $L$ simultaneously, say $(E, L) = (10,1)$, $(E, L) = (12, 0.5)$ and $(E, L) = (15, 0.33)$. One way you may think of in order to accomplish this in Python is using a loop together with the **zip** function:

In [5]:
input_E = [10,12,15]
input_L = [1,0.5,0.33]
for item_E, item_L in zip(input_E, input_L):
    print(cobb_douglas(item_E, item_L))

3.1622776601683795
2.4494897427831783
2.224859546128699


This works fine, but is not the most efficient solution. In particular, for large inputs, loops can take quite some time to execute. What would preferable instead is if we could insert lists of numbers (instead of scalars) in the function. The technical term of doing this is to perform *vectorized operations* on the input arrays. While this is a great idea, unfortunately it won't work with lists:

In [6]:
# print(cobb_douglas([10, 12, 15], [1, 0.5, 0.33])) # this will throw an error!

It will work with a different type of array, namely a NumPy array.

## NumPy Arrays

NumPy introduces a new type of array: *numpy.ndarray* (n-dimensional array). A one-dimensional NumPy array shares some features with a Python list: it contains a sequence of elements, which can be of any type (e.g. integers or strings). The elements are ordered and you can access them by position, using the slicing notation introduced above (with the first element indexed by 0 etc.). You can also use NumPy arrays in for-loops, iterating over its elements. 

In fact, one way to get a NumPy array is to take a list and convert it using the **np.array** function.

In [7]:
names = ['Daenerys', 'Tyrion', 'Arya', 'Samwell']  # start with a list, here of strings

names_np = np.array(names)  # define a NP array
print(names_np)
print(type(names_np))

['Daenerys' 'Tyrion' 'Arya' 'Samwell']
<class 'numpy.ndarray'>


In [8]:
print(names_np[0])    # access first element
print(names_np[1:3])  # access second and third element

for item in names_np: # loop over elements
    print(item)

Daenerys
['Tyrion' 'Arya']
Daenerys
Tyrion
Arya
Samwell


### Copying Arrays
Just as lists, NumPy arrays are mutable, i.e. can be changed. Note that this brings about the same issue as with lists if two names refer to the same array: then changing one of them will change the other as well. One option to make a copy of an array is the function **np.copy**, which will make a shallow copy of a NP array. 

As this topic is quite important when working with lists and arrays, we present some extension to copying of lists (and NP arrays) at the end of this notebook. For NP arrays and in the next paragraphs, we will use the method **copy**. Here are some examples to understand the difference between a copy and the defintion of a different name.

In [9]:
names = ['Daenerys', 'Tyrion', 'Arya', 'Samwell']  
names_np = np.array(names)  # create NP array

## define a different name that refers to the same array
heroes_np = names_np
## change array names
names_np[0] = 'Cersei'
## print array heroes
print(names_np)
print(heroes_np)

['Cersei' 'Tyrion' 'Arya' 'Samwell']
['Cersei' 'Tyrion' 'Arya' 'Samwell']


In [10]:
names_np = np.array(names)  # create NP array

# Solution (if necessary)
heroes_np = names_np.copy()  # define heroes_np as a copy of names_np
names_np[0] = 'Cersei'
print(names_np)
print(heroes_np)

['Cersei' 'Tyrion' 'Arya' 'Samwell']
['Daenerys' 'Tyrion' 'Arya' 'Samwell']


## Vectorized Operations
Despite their similarities, there are some key differences between lists and NumPy arrays. First, each element in a NP array must be of the *same type*, for example all elements must be strings or all integers. Second, NP arrays allow for *vectorized operations*. Essentially, a vectorized operation applies a command to every element in an array. Consider the basic arithmetic operations. Recall from above that using **+** on two lists would concatenate them, while a **-** operation is not defined on lists. With NP arrays, in contrast, addition of two arrays of the same length works as a vectorized operation, adding up the elements by position (*elementwise addition*). An analogous operation is performed in the case of subtraction, multiplication and division. Finally, *scalar multiplication* multiplies each element of the NP array with an integer or a float.    

In [11]:
ls = [1, 2, 3, 4]   # list

A = np.array(ls) # turn list NP into array
B = 5 * A   # scalar multiplication using NP arrays

print('A = ', A)
# print (ls*5) # Compare with list
print('B = ', B)

A =  [1 2 3 4]
B =  [ 5 10 15 20]


In [12]:
print('B + A = ', B + A)  # elementwise addition 
print('B - A = ', B - A)  # elementwise subtraction 
print('B * A = ', B * A)  # elementwise multiplication 
print('B / A = ', B / A)  # elementwise subtraction 

B + A =  [ 6 12 18 24]
B - A =  [ 4  8 12 16]
B * A =  [ 5 20 45 80]
B / A =  [ 5.  5.  5.  5.]


#### Universal Functions

In addition to the basic arithmetic operations, *vectorized functions* (also called "universal functions" or *ufuncs*, since they accept both numbers and sequences as arguments) are another example of vectorized operations. Important examples are **np.log** and **np.exp**, which apply the natural logarithm and the exponential function, respectively, elementwise on a sequence. Note that NumPy's vectorized function accept not only NP arrays as arguments, but all types of ordered arrays like lists and tuples. However, the returned object will always be a NP array. 

In [13]:
print(np.log(ls))        # use np.log on a list
print(type(np.log(ls)))  # argument: list -> returns a NP array
print(type(np.log(A)))   # argument: NP array -> returns a NP array

[ 0.          0.69314718  1.09861229  1.38629436]
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


#### Statistical Functions and Methods

In addition, there are a number of useful functions that operate on the whole array and return some statistic, for example the mean, standard deviation, maximum/minimum value or the sum. Again, you can apply these functions to any array: 

In [14]:
print(np.mean(ls))       # use np.mean() on a list to get the mean

print(np.mean(A))        # use np.mean() on NP array to get the mean
print(np.std(A))        # standard deviation
print(np.max(A))        # maximum value

2.5
2.5
1.11803398875
4


In the case of NumPy arrays, these functions can be used as methods (which is the more common way to use them):

In [15]:
# use methods instead
print(A.mean())   # use .mean() method
print(A.std())    # use .std() method
print(A.max())    # use .max() method
print(A.min())    # use .min() method
print(A.sum())    # use .sum() method

2.5
1.11803398875
4
1
10


In [16]:
# other useful methods
print(A.cumsum()) # cumulative sum
print(A.cumprod()) # cumulative product

[ 1  3  6 10]
[ 1  2  6 24]


In [17]:
# finding the position of the minimum and maximum
print(A)
print(A.argmax())    # use .argmax() method
print(A.argmin())    # use .argmin() method
# replacing the minimum
A[A.argmin()] = A.sum()
print(A)

[1 2 3 4]
3
0
[10  2  3  4]


## Why use NumPy and Vectorized Operations

The ability to use vectorized operations and fast array processing is the very point of NumPy. While you can perform some vectorized operations on Python lists, you should always use NumPy arrays instead, in particular for large arrays of integers or floats. In other words, when working with a lot of data stored in arrays, using a NumPy array will be significantly faster than using a Python list. There are some technical reasons for this, which you can read up on in the Quant-Econ section on Numpy (or in other sources). Moreover, you should *use vectorized operations whenever possible*, rather than use loops in Vanilla Python. Not only does this make your code more concise and hence improves readability, it can also make your code run faster considerably. In other words, vectorized operations speed up programming, both in terms of time it takes to run code and time it takes to write it (Side note: the time it takes to complete a programming project is the *sum of the time spent writing the code and the time that the computer spends running it*. Good programming should always strive to *minimize* this sum.)

#### Vectorized Operations: Example
As an example, suppose you want to create an array of a large number (say $N = 10,000,000$) of random draws from a uniform distribution and then compute the mean. Without using NumPy, your first crack at the problem may be to write a for-loop that starts with an empty list and in every iteration, performs a random draw and adds it to the list. This idea is implemented in the function **draw_unif**. Note that in Vanilla Python, the function **random()** in the module **random** implements a single draw from a uniform distribution.

In [19]:
import random

def draw_unif(N):
    ls = []
    for i in range(N):
        ls.append(random.random())
    return ls    
    
N = int(1e+7)  # alternative way to write N = 10000000

In addition, I implement the same function, but instead of an empty list, I initialize the loop with an empty NP array of length N. The advantage of this is that the computer knows in advance how large the array will be that the function returns. Note that in this case, the function **draw_unif_np** returns a NumPy array. 

In [20]:
def draw_unif_np(N):
    npa = np.zeros(N)
    for i in range(N):
        npa[i] = random.random()
    return npa 

I can "time" the time it takes to run these functions by using what is called an *IPython magic*, basically useful commands you can use in the IPython shell or a Jupyter notebook. Here, I add the command **%time** before running the function:

In [21]:
%time np.mean(draw_unif(N))  

CPU times: user 2.36 s, sys: 183 ms, total: 2.55 s
Wall time: 2.54 s


0.50009116504466011

The user CPU time and system CPU time are the amount of time spent in user space and the amount of time spent in kernel space (see https://en.wikipedia.org/wiki/User_space if you are interested in that). The wall time is the elapsed time, including time spent waiting for its turn on the CPU. If you are running other programs at the same time, wall time might be higher than CPU time. On the other hand, if you are executing code in parallel mode (computing on several CPUs at the same time), the wall time could be smaller than the CPU time.

In [22]:
%time draw_unif_np(N).mean()

CPU times: user 2.06 s, sys: 38.3 ms, total: 2.1 s
Wall time: 2.1 s


0.49998250314098208

Timing the two functions shows that the implementation with a NumPy array is a bit faster than the one using a list. Next, I use what is called a *list comprehension*, which is a more efficient one-line implementation of the **draw_unif** function. As we can see, this is even slightly faster than the standard loop with a NumPy array:

In [23]:
%time np.mean([random.random() for i in range(N)]) 

CPU times: user 1.84 s, sys: 168 ms, total: 2 s
Wall time: 2 s


0.49988210029863678

Finally, I use a fully vectorized operation in NumPy. Its subpackage **random** (which is a different module than Vanilla Python's module of the same name) contains a vectorized function **uniform(a, b, N)** that performs N random draws from the interval $[a,b]$. This implementation performs the same task in *less than 1/10* of the time that it takes Vanilla Python.

In [24]:
%time np.random.uniform(0, 1, N).mean()

CPU times: user 165 ms, sys: 31.9 ms, total: 197 ms
Wall time: 196 ms


0.499892682967709

## Two-dimensional Arrays

Another big advantage of NumPy compared to standard Python arrays is working in two dimensions, i.e. with matrices. While you can represent a matrix as a list of lists in Vanilla Python, 2D NumPy arrays are not only more memory efficient, but also more convenient to work with and have a lot of useful functions and methods, in particular when doing Linear Algebra.

There are different ways to create a 2D NumPy array. One is, similar to above, using the **np.array()** function on a list of lists. Alternatively, you can write all elements in a simple list, apply **np.array()** and then use the **shape** attribute to give the array the desired *dimension*:

In [25]:
# create 2-by-2 array from list of lists
ls = [[1,2],[3,4]]
A = np.array(ls)
print(A)

[[1 2]
 [3 4]]


In [26]:
# create 2-by-2 array from list and using shape 
B = np.array([1,2,3,4])
B.shape = (2,2)
print(B)

print(B.shape)  # print shape of B

[[1 2]
 [3 4]]
(2, 2)


**shape** takes a tuple with two elements: the first one represents the number of rows in the array, the second the number of columns. Of course, you have to make sure that the number of elements in the original list ([1,2,3,4]) equals the number of elements implied by the given dimension, here 2x2 = 4 - otherwise you will get an error. Moreover, note how NumPy applies the shape: it fills the 2D array row by row (rather than column by column).

You can also use the **shape** attribute to access an array's dimension. Note that a one-dimensional array, as defined above is by default *flat*: its dimension is *not*, for example, 4-by-1 (column vector) or 1-by-4 (row vector), but instead given as (4,). In order to change its dimension to (4,1) or (1,4) - and thus turn it into a *two-dimensional* array - you can use the **shape** attribute. 

In [27]:
A = np.array([1,2,3,4])
print('A flat 1D array', A, 'with dimension', A.shape)

A flat 1D array [1 2 3 4] with dimension (4,)


In [28]:
# turn A into a 4-by-1 column vector
A.shape = (4,1)
print('A column vector', A, 'with dimension', A.shape)

A column vector [[1]
 [2]
 [3]
 [4]] with dimension (4, 1)


In [29]:
# turn A into a 4-by-1 column vector
A.shape = (1,4)
print('A row vector', A, 'with dimension', A.shape)

A row vector [[1 2 3 4]] with dimension (1, 4)


#### Special Arrays

There are other ways to create particular NumPy arrays. The functions **np.zeros** and **np.ones** create arrays filled with zeros and ones, respectively, where the input argument determines the number of elements. You can make them two-dimensional arrays right away by giving them the intended dimension, again as a tuple. The functions **np.eye** and **np.identity** create the identity matrix. Since this is by default a two-dimesional *square* matrix (number of rows = number of columns), it takes only one integer as an argument. **np.linspace(x, y, N)** is very useful for setting up a 1D array of N evenly spaced numbers between x and y.

In [30]:
Z = np.zeros(3)
print('A flat 1D array', Z, 'with dimension', Z.shape)

O = np.ones((2,2))
print('A 2D array', O, 'with dimension', O.shape)

I = np.eye(2)
print('The identity matrix', I, 'with dimension', I.shape)

G = np.linspace(1, 3, 5)
print('A flat 1D array', G, 'with dimension', G.shape)

A flat 1D array [ 0.  0.  0.] with dimension (3,)
A 2D array [[ 1.  1.]
 [ 1.  1.]] with dimension (2, 2)
The identity matrix [[ 1.  0.]
 [ 0.  1.]] with dimension (2, 2)
A flat 1D array [ 1.   1.5  2.   2.5  3. ] with dimension (5,)


#### Indexing and Slicing

As mentioned above, for a flat array, indexing is the same as standard Python sequences. For 2D arrays, the notation is similar, but using two indices, one for rows and one for columns. For example, **A[0, 1]** accesses the element in array A which is in the *first row* (indices start at 0!) and *second column*. The slicing notation introduced for list is generalized in order to access multiple elements. 

In [31]:
A = np.array([[1,2,3], [4,5,6], [7,8,9]])  # create 2D array with dimension 3-by-3

print(A[0, 1])    # print element in first row, second column
print(A[-1, -1])  # print element in last row, last column

2
9


In [32]:
print(A[:,1])     # print second column; NB: resulting array is flat!
print(A[2,:])     # print third row; NB: resulting array is flat!
print(A[:2,:2])   # print elements in first two rows and first two columns

[2 5 8]
[7 8 9]
[[1 2]
 [4 5]]


2D NumPy arrays can use the same methods as flat arrays. For example, using the **.mean()** method without an argument gives you the mean value across *all* elements in an array. In addition, you can also compute the mean for each column or each row separately, using **axis = 0** (across rows) and **axis = 1** (across columns). 

In [33]:
print(A)
print(A.mean())         # mean across all elements
print(A.mean(axis = 0)) # mean for each column, across rows
print(A.mean(axis = 1)) # mean for each row, across columns

[[1 2 3]
 [4 5 6]
 [7 8 9]]
5.0
[ 4.  5.  6.]
[ 2.  5.  8.]


#### Vectorized Operations

Vectorized operations work in the same way as they do for flat arrays. Vectorized functions such as **np.log** are applied to each element in the 2D array, while operations such as addition work elementwise; of course that implies that the two arrays you add must have the same dimension. Caution: **A * B** performs elementwise multiplication, *not matrix multiplication*. Adding a scalar to a 2D array or multiplying a 2D array with a scalar works as expected. Finally, note that *comparisons* (e.g. A > 2 or A > B) are also done elementwise, resulting in a 2D arrays of Booleans with the same dimension as A.

In [34]:
A = np.array([[1,2,3], [4,5,6], [7,8,9]])  # create 2D array with dimension 3-by-3
B = np.ones((3,3))

print(np.log(A))    # apply vectorized function

[[ 0.          0.69314718  1.09861229]
 [ 1.38629436  1.60943791  1.79175947]
 [ 1.94591015  2.07944154  2.19722458]]


In [35]:
print(A + B)        # elementwise addition        
print(A * B)        # elementwise multiplication

[[  2.   3.   4.]
 [  5.   6.   7.]
 [  8.   9.  10.]]
[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]]


In [36]:
print(A + 4)        # adding a scalar
print(A * 2)        # multiplying with a scalar

[[ 5  6  7]
 [ 8  9 10]
 [11 12 13]]
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [37]:
print(A > 2)        # elementwise comparison to a scalar
print(A > 3 * B)    # elementwise comparison between two arrays

[[False False  True]
 [ True  True  True]
 [ True  True  True]]
[[False False False]
 [ True  True  True]
 [ True  True  True]]


#### Index Arrays

Note that the last example gives rise to NumPy *index arrays*. As an example, say you want to find all elements in a 1D or 2D array that are greater than 2. A straightforward way would be to use a loop, i.e. go through all elements in the array and check each of them successively, storing the ones that satisfy the condition. However, there is a *vectorized* and hence much faster option. The key idea is that you can use NumPy arrays that consists of booleans as index arrays for other arrays, assuming they have the same dimension. Consider a simple example:

In [38]:
Q = np.array([1, 2, 3])
P = np.array([True, True, False])
print(Q[P])

[1 2]


Basically, you keep only the elements of Q that correspond to a **True** Boolean in P. Using this idea, we can define B as **B = A > 2** and then use **A[B]** in order to get all elements of A greater than 2. In fact, we do not even have to define B, but can access these elements direcly: 

In [39]:
print(A[A > 2])

[3 4 5 6 7 8 9]


In the same way, we can also change single values of the array depending on one or multiple conditions:

In [40]:
B = A.copy()
B[B > 5] = 0
print(B)

[[1 2 3]
 [4 5 0]
 [0 0 0]]


It is also possible to have multiple conditions with the & (and) or the | (or) operators.

In [41]:
B[(B > 2) & (B < 5)] = 0
# alternative 
# B[np.logical_and(B > 2, B < 5)] = 0 
print(B)

[[1 2 0]
 [0 5 0]
 [0 0 0]]


In [42]:
C = A.copy()
C[(C > 2) & (C < 5)] = C[(C > 2) & (C < 5)]**2
# alternatively: 
# C[(C > 2) & (C < 5)] **=2
print(C)

[[ 1  2  9]
 [16  5  6]
 [ 7  8  9]]


In [43]:
C = A.copy()
C[(C > 5) | (C < 3)] = C[(C > 5) | (C < 3)]**2
# alternatively: 
# C[(C > 2) | (C < 5)] **=2
print(C)

[[ 1  4  3]
 [ 4  5 36]
 [49 64 81]]


It might also be useful to see where the elements that satisfy one or more conditions are located in an array. The function **np.where()** returns a tuples that contains a list of the row indices and a list of the column indices of those elements that satisfy the conditions:

In [44]:
print(np.where(A > 2))
rows, columns = np.where(A > 2)

## use zip function to get index pairs
for idxr, idxc in zip(rows, columns):
    print(A[idxr, idxc])

(array([0, 1, 1, 1, 2, 2, 2]), array([2, 0, 1, 2, 0, 1, 2]))
3
4
5
6
7
8
9


#### Matrix Multiplication

*Matrix multiplication* is an important operation in the context of linear algebra. For Python 3.5 and above, you can use the **@** symbol for matrix multiplication. In ealier version, you have to use **np.dot(A, B)**.

In [45]:
A = np.array([[1,2], [4,5], [7,8]])  # create 2D array with dimension 3-by-2
B = np.ones((2,4))

print(A @ B)

[[  3.   3.   3.   3.]
 [  9.   9.   9.   9.]
 [ 15.  15.  15.  15.]]


The usual requirement for matrix multiplications apply. In particular, the number of columns of the first array must be equal to the number of row in the second array. 

For flat arrays, matrix multiplication gives the inner product: 

In [46]:
A = np.array([1,2,3,4])
B = np.array([1,1,1,1])
print(A @ B)
print(B @ A)


10
10


## Multidimensional Arrays
As the name of ndarray stems from n-dimensional array, we want to point to the fact that NP arrays are not restricted to 2 dimensions. We will not go into details here but just have a look at basic properties. One option to generate a 3-D array is to stack two 2-D arrays with the function **np.stack**. The argument *axis* is optional and give the direction (in the 3-D Array), in which the input arrays are stacked.

In [48]:
A = np.array([[1,2,3], [4,5,6], [7,8,9]])  # create 2D array with dimension 3-by-3
B = np.ones((3,3))

S = np.stack((A, B), axis = 0)
print(S)
print(S.shape)

[[[ 1.  2.  3.]
  [ 4.  5.  6.]
  [ 7.  8.  9.]]

 [[ 1.  1.  1.]
  [ 1.  1.  1.]
  [ 1.  1.  1.]]]
(2, 3, 3)


Multidimensional arrays can also be also be constructed by **np.ones** or **np.zeros** and can have more than 3 dimensions as well

In [50]:
# 4-dimensional array filled with ones and two elements in each dimension
Om = np.ones((2,2,2,2))
print(Om)

[[[[ 1.  1.]
   [ 1.  1.]]

  [[ 1.  1.]
   [ 1.  1.]]]


 [[[ 1.  1.]
   [ 1.  1.]]

  [[ 1.  1.]
   [ 1.  1.]]]]


In [51]:
# 4-dimensional array of zeros, diffent number of elements in the dimensions
Zm = np.zeros((2,2,3,4))
print(Zm)

[[[[ 0.  0.  0.  0.]
   [ 0.  0.  0.  0.]
   [ 0.  0.  0.  0.]]

  [[ 0.  0.  0.  0.]
   [ 0.  0.  0.  0.]
   [ 0.  0.  0.  0.]]]


 [[[ 0.  0.  0.  0.]
   [ 0.  0.  0.  0.]
   [ 0.  0.  0.  0.]]

  [[ 0.  0.  0.  0.]
   [ 0.  0.  0.  0.]
   [ 0.  0.  0.  0.]]]]


The elements of the array can be accessed by a vector with the position in each dimension, e.g [1,3,2] accesses the second element in the first dimension, the fourth element in the second dimensions and the third element in the third dimension.

In [52]:
Zm[0,1,0,0] = 1
print(Zm)
#Zm[0,:,:,:] = 1
#print(Zm)

[[[[ 0.  0.  0.  0.]
   [ 0.  0.  0.  0.]
   [ 0.  0.  0.  0.]]

  [[ 1.  0.  0.  0.]
   [ 0.  0.  0.  0.]
   [ 0.  0.  0.  0.]]]


 [[[ 0.  0.  0.  0.]
   [ 0.  0.  0.  0.]
   [ 0.  0.  0.  0.]]

  [[ 0.  0.  0.  0.]
   [ 0.  0.  0.  0.]
   [ 0.  0.  0.  0.]]]]


## Taking Stock

Recall from above that we have defined a Cobb-Douglas production function that can take scalars (integer or floats) as arguments. For convenience, it is defined again below. We also noted that if we want to compute the output for several *(E,L)* combinations simultaneously, we need to use a loop since the function could not operate on Python lists. In fact, in terms of the terminology that we learnt in this section, what we want our **cobb_douglas** function to do is to be able to perform a vectorized operation on two arrays of inputs. It should not come as a surprise that the function does exactly that when we use NumPy arrays rather than lists as input arguments:

In [53]:
def cobb_douglas(E, L, alpha = 0.5):
    """
    Implements the Cobb-Douglas production function: y = E**alpha * L**alpha
    """
    y = E**alpha * L**(1 - alpha)
    return y

# run the function with NP arrays as inputs
print(cobb_douglas(np.array([10, 12, 15]), np.array([1, 0.5, 0.33]), 0.33)) 

[ 2.13796209  1.42705172  1.16282525]


## Appendix: Copying Arrays (and Lists)
Just as lists, NumPy arrays are mutable, i.e. can be changed. Note that this brings about the same issue as with lists if two names refer to the same array: then changing one of them will change the other as well. As this topic is quite important when working with lists and arrays, we present some extension to copying of lists here. Generally, copies can be disguingished between *shallow* and *deep* copies. While a *deep* copy also copies objects that are part of the list (e.g. list in list), a shallow copy would point to the same nested list. To understand the difference, several methods for lists are compared here: **list.copy()** (shallow copy), **slicing** (shallow copy), **copy.copy** (shallow) and **copy.deepcopy** from the module copy. If you need a copy and don't care that much about memory, we would suggest to always make deep copies of lists. If you are sure you are using only a flat list, you can also use a method for shallow copies.

In [29]:
# Import the module copy
import copy

# Simple List
a1 = [1, 2, 3, 4]
b1 = a1[:] #shallow copy
c1 = copy.deepcopy(a1) # deep copy
d1 = a1.copy() #shallow copy
e1 = copy.copy(a1) #shallow copy
# We set values of the copies to 0 at different positions to see which of them changes the orginal 
b1[0] = 0
c1[1] = 0
d1[2] = 0
e1[3] = 0
# And print the original list
print(a1)

[1, 2, 3, 4]


In [30]:
# Nested List
a2 = [[1], [2], [3], [4]]
b2 = a2[:] # shallow copy
c2 = copy.deepcopy(a2) # deep copy
d2 = a2.copy() # shallow copy
e2 = copy.copy(a2) # shallow copy
# We set values of the copies to 0 at different positions to see which of them changes the orginal 
b2[0][0] = 0
c2[1][0] = 0
d2[2][0] = 0
e2[3][0] = 0
# And print the original list
print(a2)

[[0], [2], [0], [0]]


In NumPy, you can make a copy of an array by using the **np.copyto** function or the **np.matrix.copy()** method in addition to the functions of the **copy** module. In contrast to lists, slicing by [:] does not lead to a copy of the array. However, to make life a bit easier, all copies of NumPy arrays are deep copies and you don't need to worry about this. As all elements of a NumPy Array consist of identical type, there is hardly any need for shallow copies.

In [31]:
# Simple NP Array
a3 = np.array([1, 2, 3, 4, 5])
b3 = a3[:] # not a copy!
c3 = copy.deepcopy(a3) # deep copy
d3 = a3.copy() # deep copy
e3 = copy.copy(a3) # deep copy
f3 = np.empty_like(a3)
np.copyto(f3,a3) # deep copy
# We set values of the copies to 0 at different positions to see which of them changes the orginal 
b3[0] = 0
c3[1] = 0
d3[2] = 0
e3[3] = 0
f3[4] = 0
# and print the original array
print (a3)

[0 2 3 4 5]


In [32]:
# Nested NP Array
a4 = np.array([[1], [2], [3], [4], [5]])
b4 = a4[:] # not a copy!
c4 = copy.deepcopy(a4) # deep copy
d4 = a4.copy() # deep copy
e4 = copy.copy(a4) # deep copy
f4 = np.empty_like(a4)
np.copyto(f4,a4) # deep copy           
# We set values of the copies to 0 at different positions to see which of them changes the orginal               
b4[0][0] = 0
c4[1][0] = 0
d4[2][0] = 0
e4[3][0] = 0
f4[4] = 0
# and print the original array
print (a4)

[[0]
 [2]
 [3]
 [4]
 [5]]
